### ISSUE TITLE
Incorrect prompt for class diagram

### ISSUE THREAD

**Issue by luttje** [luttje/mermaid-gpt#5]
This line of code isn't suitable for class diagrams:
https://github.com/luttje/mermaid-gpt/blob/4b3f1ba29d2f6812902be9fcb56dd7d5bd9cfa3b/src/lib/diagram-prompts.ts#L16

It's surprising how well the prompt even works for class diagrams, despite this error.

I have no intention of fixing this now, but will handle it when I add more diagram types in the future.

**Comment by Ankit8848** [comment]
@luttje what to change here, as I am a beginner. Can you guide me?

**Comment by luttje** [comment]
Heya @Ankit8848, thanks for wanting to contribute. I can sure try to help guide you!

The problematic `generateDiagram` function in diagram-prompts.ts needs to use a different "suffix" for each diagram type. Much the same way the diagram type specific prompt is used (`this.prompt`):
https://github.com/luttje/mermaid-gpt/blob/4b3f1ba29d2f6812902be9fcb56dd7d5bd9cfa3b/src/lib/diagram-prompts.ts#L16
Instead of always concatenating `+ '"""\nERDiagram code: '` you would want to concatenate a diagram specific suffix (e.g: `'"""\n' + DIAGRAM SPECIFIC SUFFIX HERE + ': '`)

In order to expand the system it would be easiest if you add a field through the constructor here: https://github.com/luttje/mermaid-gpt/blob/4b3f1ba29d2f6812902be9fcb56dd7d5bd9cfa3b/src/lib/diagram-prompts.ts#L5

Then where the types of diagrams are defined you should fill the value for that newly added field in the constructor: https://github.com/luttje/mermaid-gpt/blob/4b3f1ba29d2f6812902be9fcb56dd7d5bd9cfa3b/src/lib/diagram-prompts.ts#L44

For example for the first diagram type (Entity Relationship Diagram) you would supply the constructor with the value: `'ERDiagram code'`. For the second diagram type (class diagram) you would supply the value `'Class Diagram code'`. I'm basing those on what I explain to the AI in the prompt here: https://github.com/luttje/mermaid-gpt/blob/4b3f1ba29d2f6812902be9fcb56dd7d5bd9cfa3b/src/lib/prompts/class-diagram.ts#L7

Sadly I won't be able to assist much further as I'm busy the coming month. Nevertheless feel free to ask questions here. I'll answer when I have time.

Thanks again for your interest!
